### ISSUE TITLE
Deploy One Note Add in 

### ISSUE THREAD

**Issue by Tsathyapriya80** [OfficeDev/Office-Addin-TaskPane#195] opened 2023-01-04 00:00 UTC
@davidchesnut, 
# Prerequisites
One Note add-in deployment

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [X ] I am running the latest version of Node and the tools
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

# Expected behavior

Deploy one note add-in in the Organization for specific users or groups

# Current behavior
In the Centralized app deployment, I don't see the option to deploy for the One Note add-in, Also, it is integrated with the single sign-on. 

## Steps to Reproduce

1. Create one note add-in with <webapplication> or single sign-on
2. Deploy add-ins in the organization for specific users or groups

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Node version:
* Office version:
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by Tsathyapriya80** [comment] 2023-01-06 16:24
@davidchesnut  could you please confirm whether this option is available . when I try to upload from Centralized app -> one note add-in manifest XML. I am getting error:
Unable to upload this add-in as the associated product is not supported.
(e12ebfac-48dc-4370-b526-f8b13e7c90ed)

**Comment by davidchesnut** [comment] 2023-01-06 21:53
Hi @Tsathyapriya80, thanks for letting us know about this issue. I'm taking a look.

**Comment by davidchesnut** [comment] 2023-02-06 17:10
Hi @Tsathyapriya80, sorry this took a while. The team confirmed to me that central deployment is not supported for OneNote add-ins. This would be a good feature request if you want to submit one at [Microsoft 365 dev suggestions](https://aka.ms/m365dev-suggestions). It looks like the only deployment option right now is to use AppSource. For more information, see [Make your solutions available in Microsoft AppSource and within Office](https://learn.microsoft.com/azure/marketplace/submit-to-appsource-via-partner-center).

Cheers,
David

**Comment by AlexJerabek** [comment] 2023-04-25 17:52
Closing this issue as a product feature request.

**Closed by AlexJerabek** 2023-04-25 17:52 UTC
Labels: needs triage
